#---- begin snakebids boilerplate ----------------------------------------------

import snakebids
from snakebids import bids

configfile: workflow.source_path('../config/snakebids.yml')

# Get input wildcards
inputs = snakebids.generate_inputs(
    bids_dir=config["bids_dir"],
    pybids_inputs=config["pybids_inputs"],
    pybids_database_dir=config.get("pybids_db_dir"),
    pybidsdb_reset=True,
    derivatives=config.get("derivatives", None),
    participant_label=config.get("participant_label", None),
    exclude_participant_label=config.get("exclude_participant_label", None),
    use_bids_inputs=True,
)

#this adds constraints to the bids naming
wildcard_constraints:  **snakebids.get_wildcard_constraints(config['pybids_inputs'])

#---- end snakebids boilerplate ------------------------------------------------

include: "rules/preprocessing.smk"
include: "rules/run_inference.smk"
include: "rules/run_simulation.smk"
include: "rules/estimate_parameters.smk"


rule all:
    input:
        final=expand(rules.estimate_parameters.output.maps,zip,**inputs['dwi'].input_zip_lists)
    default_target: True